main:
#  - name: 分类
#    url: '/categories/'
#    weight: 1
#  - name: 标签
#    url: '/tags/'
#    weight: 2


  - name: 札记 
    url: '/Notes/'
    weight: 2
  - name: 随想
    url: '/categories/随想/'
    weight: 3
  - name: 自救
    url: '/categories/youcan/'
    weight: 4
  - name: 关于我
    url: '/about_me/'
    weight: 5
#  - name: Docs
#    url: /docs/
#    weight: 3